# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

---
AWSTemplateFormatVersion: "2010-09-09"
Description: Organization reference architecture for SMB - Systems Manager Parameters

Parameters:
  pManagementAccountId:
    Type: String
    Description: AWS Account ID for Management Account
    ConstraintDescription: "must only contain numbers"
    AllowedPattern: "^[0-9]{12}$"
  pOrganizationId:
    Type: String
    Description: Organization ID
    ConstraintDescription: "must only contain lowercase letters and numbers"
    AllowedPattern: "^o\\-[a-z0-9]+"
  pCloudFormationRoleName:
    Type: String
    Description: CloudFormation IAM role name
    Default: CloudFormationRole
    ConstraintDescription: "must only contain uppercase and lowercase letters and numbers"
    AllowedPattern: "[a-zA-Z0-9]+"
  pServiceCatalogRoleName:
    Type: String
    Description: ServiceCatalog IAM role name
    Default: ServiceCatalogRole
    ConstraintDescription: "must only contain uppercase and lowercase letters and numbers"
    AllowedPattern: "[a-zA-Z0-9]+"

Resources:
  ManagementIdParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: text
      Description: Management AWS Account ID
      Name: /org/core/accounts/management
      Tier: Standard
      Type: String
      Value: !Ref pManagementAccountId

  OrganizationIdParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: text
      Description: Organization ID
      Name: /org/core/organization-id
      Tier: Standard
      Type: String
      Value: !Ref pOrganizationId

  CloudFormationRoleNameParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: text
      Description: CloudFormation IAM role name
      Name: /platform/iam/CloudFormationRole
      Tier: Standard
      Type: String
      Value: !Ref pCloudFormationRoleName
  
  CloudFormationRoleArnParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: text
      Description: CloudFormation IAM role ARN
      Name: /platform/iam/CloudFormationRoleArn
      Tier: Standard
      Type: String
      Value: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${pCloudFormationRoleName}"
  
  ServiceCatalogRoleNameParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: text
      Description: ServiceCatalog IAM role name
      Name: /platform/iam/ServiceCatalogRole
      Tier: Standard
      Type: String
      Value: !Ref pServiceCatalogRoleName
  
  ServiceCatalogRoleArnParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: text
      Description: ServiceCatalog IAM role ARN
      Name: /platform/iam/ServiceCatalogRoleArn
      Tier: Standard
      Type: String
      Value: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${pServiceCatalogRoleName}"
